export const strings = {
  Appearences: 'Appearences',
  Assists: 'Assists',
  Canadian: 'Canadian',
  Career: 'Career',
  Coach_not_found: 'Coach not found',
  Conceded: 'Conceded',
  Data_not_found: 'Data not found',
  Fixtures: 'Fixtures',
  Goals: 'Goals',
  Home: 'Home',
  Leagues: 'Leagues',
  Lineups: 'Lineups',
  Games: 'Games',
  Loading: 'Loading...',
  Minutes: 'Minutes',
  Player_not_found: 'Player not found',
  Rating: 'Rating',
  Red_Cards: 'Red Cards',
  Show_more: 'Show more',
  Standings: 'Standings',
  Statistics: 'Statistics',
  Top_Asists: 'Top Asists',
  Top_Scorers: 'Top Scorers',
  Trophies: 'Trophies',
  Yellow_Cards: 'Yellow Cards',
  Transfers: 'Transfers',
  Sidelined: 'Sidelined',
  Goalkeepers: 'Goalkeepers',
  Defenders: 'Defenders',
  Midfielders: 'Midfielders',
  Attackers: 'Attackers',
  Players: 'Players',
  Age: 'Age',
  Since: 'Since',
  Position: 'Position',
  Birthdate: 'Birthdate',
  Birthplace: 'Birthplace',
  Nationality: 'Nationality',
  Height: 'Height',
  Weight: 'Weight',
  Role: 'Role',
  Coach: 'Coach',

  leagues: {
    Premier_League: 'Premier League',
    La_Liga: 'La Liga',
    Ligue_1: 'Ligue 1',
    Bundesliga: 'Bundesliga',
    Serie_A: 'Serie A',
    Primeira_Liga: 'Primeira Liga',
    Ekstraklasa: 'Ekstraklasa',
    SuperLig: 'SuperLig',
    Eredivisie: 'Eredivisie',
    ProLeague: 'ProLeague',
  },
};
